//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Fragebogen_unter_Maschine
    {
        public int FragebogenNr { get; set; }
        public int F_Id_SBF_Binnen { get; set; }
    
        public virtual T_SBF_Binnen T_SBF_Binnen { get; set; }
    }
}
