//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Funk_UBI
    {
        public int Id { get; set; }
        public string Frage { get; set; }
        public string AntwortA { get; set; }
        public string AntwortB { get; set; }
        public string AntwortC { get; set; }
        public string AntwortD { get; set; }
        public string RichtigeAntwort { get; set; }
    }
}
